export enum ErrorCode {
  PATTERN_CODE = '{0} is {1}',
  NON_PATTERN_CODE = 'NON_PATTERN_CODE',
  AUTHOR_NOT_FOUND = 'AUTHOR_NOT_FOUND',
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
  BOOK_ALREADY_EXISTS = 'BOOK_ALREADY_EXISTS',
}

